version: '3'
services:
  scheduler:
    image:  scheduler:BUILD_NUMBER
    container_name: scheduler
    restart: always
    environment:
      - "JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:6011"
      - "SPRING_APPLICATION_NAME=scheduler"
      - "SPRING_PROFILES_ACTIVE=dev"
      - "SPRING_CLOUD_CONFIG_URL=http://192.168.53.58:9031"
    extra_hosts:
      - "scheduler-srv : 192.168.53.58"
    ports:
      - "9026:9026"
    volumes:
      - "/var/log/money-transfer/scheduler/:/var/log/scheduler/"
      - "/opt/configs:/opt/configs"