version: '3'
services:
  scheduler:
    image:  repo.sadad.co.ir/repository/baam-docker-registry/scheduler:latest
    container_name: scheduler
    restart: always
    ports:
      - "9026:9026"
    volumes:
      - "/var/log/money-transfer/scheduler/:/var/log/scheduler/"
      - "/opt/configs:/opt/configs"