apiVersion: v1
kind: Service
metadata:
  name: scheduler
  labels:
    app: scheduler
spec:
  selector:
    app: scheduler
  ports:
    - name: "http"
      port: 9026
      targetPort: 9026
  type: NodePort