apiVersion: v1
kind: Service
metadata:
  name: scheduler-service
  labels:
    app: scheduler-service
spec:
  selector:
    app: scheduler-service
  ports:
    - name: "http"
      port: 9026
      targetPort: 9026
  type: NodePort