server:
  port: 9026

spring:
  application:
    name: Scheduler-service
  zipkin:
    enabled: false
  sleuth:
    async:
      configurer:
        enabled: true


  standing-order-datasource:
    username: MT
    password: kjio0988
    jdbcUrl: jdbc:oracle:thin:@//172.30.41.22:1521/offpayapdb1
    driver-class-name: oracle.jdbc.OracleDriver
    hibernate:
      dialect: org.hibernate.dialect.Oracle12cDialect
      hbm2ddl-auto: update
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
  flyway:
    user: MT
    password: kjio0988
    schemas: MT
    baseline-on-migrate: true
    url: jdbc:oracle:thin:@//172.30.41.22:1521/offpayapdb1
    locations: classpath:db/migration


  thymeleaf:
    enabled=false:management:
    enabled: false
  endpoints:
    web:
      exposure:
        include: prometheus,health,info,metric,env,httptrace,loggers

logging:
  level:
    root: INFO
  file:
    name: ./logs/standing-order.log
    path: ./logs
  logback:
    rollingpolicy:
      max-file-size: 20MB
      file-name-pattern: .logs/payment-order-%d{yyyy-MM-dd}.%i.log

secretKeyLocation: /opt/configs
bmi:
  oauth2:
    excluded-urls: /index.html/**:*,/v3/api-docs/**,/swagger-ui/**:*,/h2/**:*,/swagger-ui.html:*,/webjars/**:*,/v2/**:*,/swagger-resources/**:*,/actuator/**:*,/actuator/prometheus/**:*,/trace/**:*,/enterprisebaamapi/h2/**:*,/enterprisebaamapi/swagger-ui.html:*,/enterprisebaamapi/webjars/**:*,/enterprisebaamapi/v2/**:*,/enterprisebaamapi/swagger-resources/**:*,/enterprisebaamapi/actuator/**:*,/enterprisebaamapi/actuator/prometheus/**:*,/enterprisebaamapi/trace/**:*

feign:
  client:
    eb-url: https://eb.bmi.ir
    baam-url: https://www.bmi.ir
    aggregation-url: 172.30.43.12:9095
    tan-url: 192.168.53.58:9080
    pooya-integration-url: 192.168.52.106:9383
    isc-integration-url: 192.168.53.58:9023
    iban-url: 192.168.53.23
    sso-url: 185.135.30.10:9443

sso:
  grant-type: client_credentials
  scopes: money-transfer svc-mgmt-agg-acc-part-perc-info payment-order-joint-account-transfer
  authorization: Basic am9pbnQtYWNjb3VudC1jbGllbnQ6ZEw2dkIyY0kxYlIyYkwyZkM1a0czaE04bUd2QjNlRDFmRDFmQjJnUDQ=



