server:
  port: 9026

spring:
  profiles: uat
  application:
    name: Scheduler-service
  zipkin:
    enabled: false
  sleuth:
    async:
      configurer:
        enabled: true

  scheduler-service-datasource:
    username: developer
    password:
    jdbcUrl: jdbc:oracle:thin:@//192.168.34.52:1523/MTDB
    driver-class-name: oracle.jdbc.OracleDriver
    hibernate:
      dialect: org.hibernate.dialect.Oracle12cDialect
      hbm2ddl-auto: update
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
  flyway:
    user: developer
    password:
    schemas:MT
    baseline-on-migrate: true
    url: jdbc:oracle:thin:@//192.168.34.52:1523/MTDB
    locations: classpath:db/migration

management:
  endpoints:
    web:
      exposure:
        include: prometheus,health,info,metric,env,httptrace,loggers

logging:
  level:
    root: INFO
  file:
    name: ./logs/scheduler-order.log
    path: ./logs
  logback:
    rollingpolicy:
      max-file-size: 20MB
      file-name-pattern: .logs/payment-order-%d{yyyy-MM-dd}.%i.log

secretKeyLocation: /opt/configs
bmi:
  oauth2:
    excluded-urls: /v3/api-docs/**,/swagger-ui/**:*,/h2/**:*,/swagger-ui.html:*,/webjars/**:*,/v2/**:*,/swagger-resources/**:*,/actuator/**:*,/actuator/prometheus/**:*,/trace/**:*,/enterprisebaamapi/h2/**:*,/enterprisebaamapi/swagger-ui.html:*,/enterprisebaamapi/webjars/**:*,/enterprisebaamapi/v2/**:*,/enterprisebaamapi/swagger-resources/**:*,/enterprisebaamapi/actuator/**:*,/enterprisebaamapi/actuator/prometheus/**:*,/enterprisebaamapi/trace/**:*

feign:
  client:
    eb-url: https://eb.bmi.ir
    baam-url: https://www.bmi.ir
    standing-order-url: uat-standing-order-service:9027
    sso-url: http://192.168.53.58:9080

sso:
  grant-type: client_credentials
  scopes: transaction
  authorization: Basic a2V5OnNlY3JldA==



