server:
  port: 9026
spring:
  cloud:
    config:
      uri:
        - http://192.168.53.58:9031
      enabled: true
  boot:
    admin:
      client:
        username: admin
        password: admin
        url: http://192.168.53.58:9030
        api-path: /instances
        prefer-ip: true
  application:
    name: scheduler
  zipkin:
    enabled: false
  sleuth:
    async:
      configurer:
        enabled: true
  scheduler-datasource:
    username: MT
    password: kjio0988
    jdbcUrl: jdbc:oracle:thin:@//172.30.41.22:1521/offpayapdb1
    driver-class-name: oracle.jdbc.OracleDriver
    hibernate:
      dialect: org.hibernate.dialect.Oracle12cDialect
      hbm2ddl-auto: update
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true

management:
  metrics:
    export:
      prometheus:
        enabled: true
    distribution:
      slo:
        http:
          server:
            requests: 1s,5s,30s
    enable:
      tomcat: false
      process: false
      system: false
      jdbc: false
  endpoints:
    web:
      exposure:
        include: "*"
  health:
  show-details: always

logging:
  file:
    name: ./logs/scheduler.log
    path: ./logs
  logback:
    rollingpolicy:
      max-file-size: 20MB
      file-name-pattern: .logs/scheduler-%d{yyyy-MM-dd}.%i.log

iam:
  oauth2:
    excluded-urls: /v3/api-docs/**,/swagger-ui/**:*,/h2/**:*,/swagger-ui.html:*,/webjars/**:*,/v2/**:*,/swagger-resources/**:*,/actuator/**:*,/actuator/prometheus/**:*,/trace/**:*,enterpriseapi/swagger-ui.html:*,/enterpriseapi/webjars/**:*
secretKeyLocation: /opt/configs

feign:
  client:
    config:
      feignName:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: full
        errorDecoder: webClient.standingOrder.config.StandingOrderErrorDecoder
        decode404: false
        decoder: webClient.standingOrder.config.StandingOrderDecoder
    compression:
      response:
        enabled: true
        useGzipDecoder: true
    sso-url: 192.168.53.58:9080
    standing-order-url: localhost:9027
    payment-order-url: localhost:9022
sso:
  grant-type: client_credentials
  scopes: transaction
  authorization: Basic a2V5OnNlY3JldA==
org:
  quartz:
    jobStore:
      useProperties: true
      tablePrefix: QRTZ_
      isClustered: true
      clusterCheckinInterval: 1000
      driverDelegateClass: org.quartz.impl.jdbcjobstore.oracle.OracleDelegate
      class: org.quartz.impl.jdbcjobstore.JobStoreTX
      misfireThreshold: 1000
    threadPool:
      threadCount: 20
      threadPriority: 9
      class: org.quartz.simpl.SimpleThreadPool
    scheduler:
      instanceName: spring-boot-quartz
      instanceId: AUTO